version: '3'

services:
  backendrails:
    build: ./backend
    container_name: Backend-rails
    restart: unless-stopped
    volumes:
      - ./backend:/myapp
    ports:
      - '5050:5050'
    command: 'bundle exec rails s -p 5050 -b "0.0.0.0"'
    stdin_open: true
    tty: true

  frontendreact:
    image: 'node:10-alpine'
    container_name: Frontend-React
    restart: unless-stopped
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    ports:
      - '3000:3000'
    command: 'yarn start'
